name: darrellbooker
favicon: null
layout_spectrum: 0.7584
typography_spectrum: 0.6132826174143702
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "darrell's world"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#0061a5'
    - '#93968b'
    - '#b25400'
    - '#daddcc'
  brandStrength: 0.9375
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
